apiVersion: v1
kind: Service
metadata:
  name: vnf-3
  labels:
    app: vnf-3-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  #   name: http
  # - port: 443
  #   protocol: TCP
  #   name: https
  selector:
    app: vnf-3-pod