apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnf-a
  labels:
    ratio: "100"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnf-a-pod
  template:
    metadata:
      labels:
        app: vnf-a-pod
    spec:
      schedulerName: availability-filter-and-latency-score-scheduler
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80