apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnf-2
  labels:
    ratio: "100"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vnf-2-pod
  template:
    metadata:
      labels:
        app: vnf-2-pod
    spec:
      schedulerName: availability-filter-and-latency-score-scheduler
      containers:
      - image: zzbslayer/vnf-demo
        imagePullPolicy: IfNotPresent
        name: vnf-2
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          value: "vnf-2"
        - name: APP_PORT
          value: "80"
        - name: SYS_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SYS_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: SYS_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
