# copy to /etc/kubernetes/custom-scheduler.yaml on control plane
apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
# leaderElection:
#   leaderElect: true
#   lockObjectName: scheduler-framework-sample
#   lockObjectNamespace: kube-system
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
  - schedulerName: availability-filter-and-latency-score-scheduler
    plugins:
      filter:
        enabled:
        - name: "availabilityawared"
      score:
        enabled:
        - name: "latencyawared"
        disabled:
        - name: "*"
      preBind:
        enabled:
        - name: "availabilityawared"
  - schedulerName: latency-filter-and-availability-score-scheduler
    plugins:
      filter:
        enabled:
        - name: "latencyawared"
      score:
        enabled:
        - name: "availabilityawared"
        disabled:
        - name: "*"
      preBind:
        enabled:
        - name: "availabilityawared"