apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: al-scheduler
  template:
    metadata:
      labels:
        app: al-scheduler
    spec:
      schedulerName: availability-filter-and-latency-score-scheduler
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80