apiVersion: apps/v1
kind: Deployment
metadata:
  name: la-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: la-scheduler
  template:
    metadata:
      labels:
        app: la-scheduler
    spec:
      schedulerName: latency-filter-and-availability-score-scheduler
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80